unbind r
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

unbind C-b
unbind M-f
unbind C-f
set -g prefix C-f

set -g mouse on
set-option -g status-position top
setw -g mode-keys vi

# splits
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# start from 1
set -g base-index 1
setw -g pane-base-index 1

# catppuccin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# window numbers only
set -g window-status-format "#[fg=#11111b,bg=#{@thm_overlay_2}] #I "
set -g window-status-current-format "#[fg=#11111b,bg=#{@thm_overlay_2}] #I "

# vim-aware pane navigation
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"
bind-key -n C-h if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind-key -n C-j if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind-key -n C-k if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind-key -n C-l if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'

bind-key -T copy-mode-vi C-h select-pane -L
bind-key -T copy-mode-vi C-j select-pane -D
bind-key -T copy-mode-vi C-k select-pane -U
bind-key -T copy-mode-vi C-l select-pane -R

# split window management
bind -n M-h resize-pane -L 5
bind -n M-j resize-pane -D 3
bind -n M-k resize-pane -U 3
bind -n M-l resize-pane -R 5

# Window rename
set -g automatic-rename off

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'jimeh/tmuxifier'

run '~/.tmux/plugins/tpm/tpm'
