# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, firefox
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
unbind = SUPER, D
bindd = SUPER, D, Omarchy menu, exec, omarchy-menu
unbind = SUPER, L
bind = SUPER, H, movefocus, l
bind = SUPER, L, movefocus, r
