# If not running interactively, don't do anything (leave this at the top of this file)
[[ $- != *i* ]] && return

# All the default Omarchy aliases and functions
# (don't mess with these directly, just overwrite them here!)
source ~/.local/share/omarchy/default/bash/rc
alias vim="nvim"
alias q="exit"
alias get_idf=". $HOME/devtools/esp/esp-idf/export.sh "
alias tmux-posturis="tmuxifier load-session code && tmuxifier load-session AI && tmux switch-client -n"

# Add your own exports, aliases, and functions here.
#
# Make an alias for invoking commands you use constantly
# alias p='python'
export PATH="$HOME/devtools/flutter/bin:$PATH"
export ANDROID_HOME="$HOME/devtools/Android/Sdk"
export ANDROID_SDK_ROOT="$ANDROID_HOME"
export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH"
export PATH="$HOME/.tmuxifier/bin:$PATH"
export ANDROID_AVD_HOME="$HOME/.config/.android/avd"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.tmuxifier/bin:$PATH"
export TMUXIFIER_LAYOUT_PATH="$HOME/.tmux-layouts"
eval "$(tmuxifier init -)"
fastfetch
